github: fix codeowners
multi-geth/multi-geth pull request #40
Opened 2019-02-13 14:52 UTC by whilei

Rel #34

These are not the _eternal_ or canonical
codeowners (I hope), but can serve for now
as a starting point.

They should continue to be revised as
discussions around this topic progress.

2019-02-13 20:17 UTC, sorpaas approved these changes

2019-02-13 20:19 UTC, sorpaas requested changes
Ah @whilei, I realize, that not all folders have code owners. The original purpose is probably just to notify those people if the files under those folders are changed (because they're the most knowledgeable). So I'm thinking, what do you think about if we simply remove `CODEOWNERS` file?

2019-02-14 15:49 UTC, whilei commented
Yeap, that sounds fine. Will do.

2019-02-14 16:02 UTC, sorpaas approved these changes

2019-02-14 16:02 UTC, merged